//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protobi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Protobi.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to append strip.
        /// </summary>
        internal static string append_strip {
            get {
                return ResourceManager.GetString("append_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio strip.
        /// </summary>
        internal static string audio_strip {
            get {
                return ResourceManager.GetString("audio_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current book title: {0}.
        /// </summary>
        internal static string current_title {
            get {
                return ResourceManager.GetString("current_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (untitled heading).
        /// </summary>
        internal static string default_heading {
            get {
                return ResourceManager.GetString("default_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit heading.
        /// </summary>
        internal static string edit_heading {
            get {
                return ResourceManager.GetString("edit_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading wave file.
        /// </summary>
        internal static string error_loading_wav {
            get {
                return ResourceManager.GetString("error_loading_wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        internal static string heading_level {
            get {
                return ResourceManager.GetString("heading_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 (title).
        /// </summary>
        internal static string heading_title {
            get {
                return ResourceManager.GetString("heading_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format: expected RIFF identifier, but got &quot;{0}&quot; instead..
        /// </summary>
        internal static string not_riff {
            get {
                return ResourceManager.GetString("not_riff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename strip.
        /// </summary>
        internal static string rename_strip {
            get {
                return ResourceManager.GetString("rename_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (A value is required).
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resize strip.
        /// </summary>
        internal static string resize_strip {
            get {
                return ResourceManager.GetString("resize_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strip {0}.
        /// </summary>
        internal static string strip_name {
            get {
                return ResourceManager.GetString("strip_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure strip.
        /// </summary>
        internal static string structure_strip_label {
            get {
                return ResourceManager.GetString("structure_strip_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format tag: expected 1 (PCM) but got {0} instead..
        /// </summary>
        internal static string unknown_format_tag {
            get {
                return ResourceManager.GetString("unknown_format_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format: expected 16 bits per sample, but got {0} instead..
        /// </summary>
        internal static string unsupported_bits_per_sample {
            get {
                return ResourceManager.GetString("unsupported_bits_per_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format: data chunk before format chunk..
        /// </summary>
        internal static string unsupported_data {
            get {
                return ResourceManager.GetString("unsupported_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format: more than one format chunk..
        /// </summary>
        internal static string unsupported_format {
            get {
                return ResourceManager.GetString("unsupported_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format: expected WAVE RIFF type, but got &quot;{0}&quot; instead..
        /// </summary>
        internal static string unsupported_riff_type {
            get {
                return ResourceManager.GetString("unsupported_riff_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (untitled).
        /// </summary>
        internal static string untitled {
            get {
                return ResourceManager.GetString("untitled", resourceCulture);
            }
        }
    }
}
