//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Obi.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add audio block.
        /// </summary>
        internal static string add_phrase_command_label {
            get {
                return ResourceManager.GetString("add_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add section.
        /// </summary>
        internal static string add_section_command_label {
            get {
                return ResourceManager.GetString("add_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This annotation is useful during production, but it does not appear in the exported presentation..
        /// </summary>
        internal static string annotation_tooltip {
            get {
                return ResourceManager.GetString("annotation_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply phrase detection.
        /// </summary>
        internal static string apply_phrase_detection_command_label {
            get {
                return ResourceManager.GetString("apply_phrase_detection_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset_{0}.
        /// </summary>
        internal static string asset_name {
            get {
                return ResourceManager.GetString("asset_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of this audio segment.
        /// </summary>
        internal static string audio_block_duration_tooltip {
            get {
                return ResourceManager.GetString("audio_block_duration_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A segment of audio..
        /// </summary>
        internal static string audio_block_tooltip {
            get {
                return ResourceManager.GetString("audio_block_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAVE file (*.wav)|*.wav|Any file|*.*.
        /// </summary>
        internal static string audio_file_filter {
            get {
                return ResourceManager.GetString("audio_file_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block.
        /// </summary>
        internal static string block {
            get {
                return ResourceManager.GetString("block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find channel named &quot;{0}&quot;..
        /// </summary>
        internal static string channel_not_found {
            get {
                return ResourceManager.GetString("channel_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list of recent projects?.
        /// </summary>
        internal static string clear_recent_caption {
            get {
                return ResourceManager.GetString("clear_recent_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the list of recent projects?
        ///You cannot undo this operation..
        /// </summary>
        internal static string clear_recent_text {
            get {
                return ResourceManager.GetString("clear_recent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed project &quot;{0}&quot;..
        /// </summary>
        internal static string closed_project {
            get {
                return ResourceManager.GetString("closed_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing a modified project.
        /// </summary>
        internal static string closed_project_caption {
            get {
                return ResourceManager.GetString("closed_project_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close a project with unsaved modifications.
        ///Do you want to save these modifications before closing the project?.
        /// </summary>
        internal static string closed_project_text {
            get {
                return ResourceManager.GetString("closed_project_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cop&amp;y{0}.
        /// </summary>
        internal static string copy_menu_label {
            get {
                return ResourceManager.GetString("copy_menu_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy audio block.
        /// </summary>
        internal static string copy_phrase_command_label {
            get {
                return ResourceManager.GetString("copy_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy section.
        /// </summary>
        internal static string copy_section_command_label {
            get {
                return ResourceManager.GetString("copy_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Directory.
        /// </summary>
        internal static string create_directory_caption {
            get {
                return ResourceManager.GetString("create_directory_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} could not be created: {1}.
        /// </summary>
        internal static string create_directory_failure {
            get {
                return ResourceManager.GetString("create_directory_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} does not exist. Do you want to create it?.
        /// </summary>
        internal static string create_directory_query {
            get {
                return ResourceManager.GetString("create_directory_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cut{0}.
        /// </summary>
        internal static string cut_menu_label {
            get {
                return ResourceManager.GetString("cut_menu_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut audio block.
        /// </summary>
        internal static string cut_phrase_command_label {
            get {
                return ResourceManager.GetString("cut_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut section.
        /// </summary>
        internal static string cut_section_command_label {
            get {
                return ResourceManager.GetString("cut_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move section out.
        /// </summary>
        internal static string decrease_section_level_command_label {
            get {
                return ResourceManager.GetString("decrease_section_level_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string default_organization {
            get {
                return ResourceManager.GetString("default_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled section.
        /// </summary>
        internal static string default_section_label {
            get {
                return ResourceManager.GetString("default_section_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete{0}.
        /// </summary>
        internal static string delete_menu_label {
            get {
                return ResourceManager.GetString("delete_menu_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete audio block.
        /// </summary>
        internal static string delete_phrase_command_label {
            get {
                return ResourceManager.GetString("delete_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete section.
        /// </summary>
        internal static string delete_section_command_label {
            get {
                return ResourceManager.GetString("delete_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarding changes to a modified project.
        /// </summary>
        internal static string discard_changes_caption {
            get {
                return ResourceManager.GetString("discard_changes_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to discard all modifications made to this
        ///project and revert it to its last saved state?
        ///You cannot undo this operation..
        /// </summary>
        internal static string discard_changes_text {
            get {
                return ResourceManager.GetString("discard_changes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty label.
        /// </summary>
        internal static string empty_label_warning_caption {
            get {
                return ResourceManager.GetString("empty_label_warning_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section cannot have an empty label..
        /// </summary>
        internal static string empty_label_warning_text {
            get {
                return ResourceManager.GetString("empty_label_warning_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;table of contents.
        /// </summary>
        internal static string hide_toc_label {
            get {
                return ResourceManager.GetString("hide_toc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;VU meter.
        /// </summary>
        internal static string hide_vu_meter {
            get {
                return ResourceManager.GetString("hide_vu_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move section in.
        /// </summary>
        internal static string increase_section_level_command_label {
            get {
                return ResourceManager.GetString("increase_section_level_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        internal static string listening {
            get {
                return ResourceManager.GetString("listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar&amp;k section as {0}.
        /// </summary>
        internal static string mark_section_as_used_or_unused {
            get {
                return ResourceManager.GetString("mark_section_as_used_or_unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar&amp;k {0} as {1}.
        /// </summary>
        internal static string mark_strip_or_section_as_used_or_unused {
            get {
                return ResourceManager.GetString("mark_strip_or_section_as_used_or_unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge blocks.
        /// </summary>
        internal static string merge_phrases_command_label {
            get {
                return ResourceManager.GetString("merge_phrases_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find path to asset directory..
        /// </summary>
        internal static string missing_asset_path {
            get {
                return ResourceManager.GetString("missing_asset_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string mono {
            get {
                return ResourceManager.GetString("mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move audio block.
        /// </summary>
        internal static string move_phrase_command_label {
            get {
                return ResourceManager.GetString("move_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move section down.
        /// </summary>
        internal static string move_section_down_command_label {
            get {
                return ResourceManager.GetString("move_section_down_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move strip down.
        /// </summary>
        internal static string move_section_down_linear_command_label {
            get {
                return ResourceManager.GetString("move_section_down_linear_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move section up.
        /// </summary>
        internal static string move_section_up_command_label {
            get {
                return ResourceManager.GetString("move_section_up_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move strip up.
        /// </summary>
        internal static string move_section_up_linear_command_label {
            get {
                return ResourceManager.GetString("move_section_up_linear_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        internal static string name_already_exists_caption {
            get {
                return ResourceManager.GetString("name_already_exists_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not rename item `{0}&apos; as this name is already in use in the project..
        /// </summary>
        internal static string name_already_exists_text {
            get {
                return ResourceManager.GetString("name_already_exists_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string new_project {
            get {
                return ResourceManager.GetString("new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New strip.
        /// </summary>
        internal static string new_strip_label {
            get {
                return ResourceManager.GetString("new_strip_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input device found.
        /// </summary>
        internal static string no_input_device_caption {
            get {
                return ResourceManager.GetString("no_input_device_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not select and audio input device: node found. Sorry :(.
        /// </summary>
        internal static string no_input_device_text {
            get {
                return ResourceManager.GetString("no_input_device_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is currently open..
        /// </summary>
        internal static string no_open_project {
            get {
                return ResourceManager.GetString("no_open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio output device found.
        /// </summary>
        internal static string no_output_device_caption {
            get {
                return ResourceManager.GetString("no_output_device_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not select an audio output device: none found. Sorry :(.
        /// </summary>
        internal static string no_output_device_text {
            get {
                return ResourceManager.GetString("no_output_device_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page ....
        /// </summary>
        internal static string no_page_label {
            get {
                return ResourceManager.GetString("no_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project..
        /// </summary>
        internal static string no_project {
            get {
                return ResourceManager.GetString("no_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obi.
        /// </summary>
        internal static string obi {
            get {
                return ResourceManager.GetString("obi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening project file.
        /// </summary>
        internal static string open_project_error_caption {
            get {
                return ResourceManager.GetString("open_project_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read XUK file {0}..
        /// </summary>
        internal static string open_project_error_text {
            get {
                return ResourceManager.GetString("open_project_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened XUK file {0}..
        /// </summary>
        internal static string opened_project {
            get {
                return ResourceManager.GetString("opened_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace project?.
        /// </summary>
        internal static string overwrite_file_caption {
            get {
                return ResourceManager.GetString("overwrite_file_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists.
        ///Do you want to replace the project contained in this file?.
        /// </summary>
        internal static string overwrite_file_text {
            get {
                return ResourceManager.GetString("overwrite_file_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page {0}.
        /// </summary>
        internal static string page_number {
            get {
                return ResourceManager.GetString("page_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste{0}.
        /// </summary>
        internal static string paste_menu_label {
            get {
                return ResourceManager.GetString("paste_menu_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste audio block.
        /// </summary>
        internal static string paste_phrase_command_label {
            get {
                return ResourceManager.GetString("paste_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste section.
        /// </summary>
        internal static string paste_section_command_label {
            get {
                return ResourceManager.GetString("paste_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;ause.
        /// </summary>
        internal static string pause_all {
            get {
                return ResourceManager.GetString("pause_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  phrase.
        /// </summary>
        internal static string phrase {
            get {
                return ResourceManager.GetString("phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play &amp;all.
        /// </summary>
        internal static string play_all {
            get {
                return ResourceManager.GetString("play_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play &amp;selection.
        /// </summary>
        internal static string play_selection {
            get {
                return ResourceManager.GetString("play_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing on device {0}.
        /// </summary>
        internal static string playing_on_device {
            get {
                return ResourceManager.GetString("playing_on_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create project directory {0}..
        /// </summary>
        internal static string project_directory_creation_error {
            get {
                return ResourceManager.GetString("project_directory_creation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Record.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording error.
        /// </summary>
        internal static string recorder_error_caption {
            get {
                return ResourceManager.GetString("recorder_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while recording. Sorry :(.
        /// </summary>
        internal static string recorder_error_text {
            get {
                return ResourceManager.GetString("recorder_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string redo_label {
            get {
                return ResourceManager.GetString("redo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove page label.
        /// </summary>
        internal static string remove_page_command_label {
            get {
                return ResourceManager.GetString("remove_page_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename node.
        /// </summary>
        internal static string rename_command_label {
            get {
                return ResourceManager.GetString("rename_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename audio block.
        /// </summary>
        internal static string rename_phrase_command_label {
            get {
                return ResourceManager.GetString("rename_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file {0}. ({1}).
        /// </summary>
        internal static string report_delete_error {
            get {
                return ResourceManager.GetString("report_delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resize strip.
        /// </summary>
        internal static string resize_strip {
            get {
                return ResourceManager.GetString("resize_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings.
        /// </summary>
        internal static string save_settings_error_caption {
            get {
                return ResourceManager.GetString("save_settings_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while trying to save the settings:
        ///&quot;{0}&quot;
        ///As a result, changes to the settings made during this session have not been saved.
        ///Oh well..
        /// </summary>
        internal static string save_settings_error_text {
            get {
                return ResourceManager.GetString("save_settings_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved XUK file {0}..
        /// </summary>
        internal static string saved_project {
            get {
                return ResourceManager.GetString("saved_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section.
        /// </summary>
        internal static string section {
            get {
                return ResourceManager.GetString("section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the section&apos;s name.
        /// </summary>
        internal static string section_strip_name_tooltip {
            get {
                return ResourceManager.GetString("section_strip_name_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This strip represents a single section. Audio phrases are shown inside a strip. Right-click for more options..
        /// </summary>
        internal static string section_strip_tooltip {
            get {
                return ResourceManager.GetString("section_strip_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set page label.
        /// </summary>
        internal static string set_page_command_label {
            get {
                return ResourceManager.GetString("set_page_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete strip.
        /// </summary>
        internal static string shallow_delete_section_command_label {
            get {
                return ResourceManager.GetString("shallow_delete_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;table of contents.
        /// </summary>
        internal static string show_toc_label {
            get {
                return ResourceManager.GetString("show_toc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;VU meter.
        /// </summary>
        internal static string show_vu_meter {
            get {
                return ResourceManager.GetString("show_vu_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to split block.
        /// </summary>
        internal static string split_phrase_command_label {
            get {
                return ResourceManager.GetString("split_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiding table of contents..
        /// </summary>
        internal static string status_toc_hidden {
            get {
                return ResourceManager.GetString("status_toc_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing table of contents..
        /// </summary>
        internal static string status_toc_shown {
            get {
                return ResourceManager.GetString("status_toc_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        internal static string stereo {
            get {
                return ResourceManager.GetString("stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strip.
        /// </summary>
        internal static string strip {
            get {
                return ResourceManager.GetString("strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For showing a page number.
        /// </summary>
        internal static string structure_block_tooltip {
            get {
                return ResourceManager.GetString("structure_block_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section names are shown nested in this view.  You can rename and reorder sections. Right-click for more options..
        /// </summary>
        internal static string toc_view_tooltip {
            get {
                return ResourceManager.GetString("toc_view_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark {0} as {1}.
        /// </summary>
        internal static string toggle_used_command_label {
            get {
                return ResourceManager.GetString("toggle_used_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to touch project.
        /// </summary>
        internal static string touch_command_label {
            get {
                return ResourceManager.GetString("touch_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string undo_label {
            get {
                return ResourceManager.GetString("undo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unused.
        /// </summary>
        internal static string unused {
            get {
                return ResourceManager.GetString("unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        internal static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obi project file (*.xuk)|*.xuk|Any file|*.*.
        /// </summary>
        internal static string xuk_filter {
            get {
                return ResourceManager.GetString("xuk_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of XUK file is not the current version (expected {0} but got {1} instead.).
        /// </summary>
        internal static string xuk_version_mismatch {
            get {
                return ResourceManager.GetString("xuk_version_mismatch", resourceCulture);
            }
        }
    }
}
