//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Obi.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio block.
        /// </summary>
        internal static string add_phrase_command_label {
            get {
                return ResourceManager.GetString("add_phrase_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add section.
        /// </summary>
        internal static string add_section_command_label {
            get {
                return ResourceManager.GetString("add_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset_{0}.
        /// </summary>
        internal static string asset_name {
            get {
                return ResourceManager.GetString("asset_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find channel named &quot;{0}&quot;..
        /// </summary>
        internal static string channe_not_found {
            get {
                return ResourceManager.GetString("channe_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list of recent projects?.
        /// </summary>
        internal static string clear_recent_caption {
            get {
                return ResourceManager.GetString("clear_recent_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the list of recent projects?
        ///You cannot undo this operation..
        /// </summary>
        internal static string clear_recent_text {
            get {
                return ResourceManager.GetString("clear_recent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed project &quot;{0}&quot;..
        /// </summary>
        internal static string closed_project {
            get {
                return ResourceManager.GetString("closed_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing a modified project.
        /// </summary>
        internal static string closed_project_caption {
            get {
                return ResourceManager.GetString("closed_project_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close a project with unsaved modifications.
        ///Do you want to save these modifications before closing the project?.
        /// </summary>
        internal static string closed_project_text {
            get {
                return ResourceManager.GetString("closed_project_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Directory.
        /// </summary>
        internal static string create_directory_caption {
            get {
                return ResourceManager.GetString("create_directory_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} could not be created: {1}.
        /// </summary>
        internal static string create_directory_failure {
            get {
                return ResourceManager.GetString("create_directory_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} does not exist. Do you want to create it?.
        /// </summary>
        internal static string create_directory_query {
            get {
                return ResourceManager.GetString("create_directory_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string default_organization {
            get {
                return ResourceManager.GetString("default_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled section.
        /// </summary>
        internal static string default_section_label {
            get {
                return ResourceManager.GetString("default_section_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete section.
        /// </summary>
        internal static string delete_section_command_label {
            get {
                return ResourceManager.GetString("delete_section_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarding changes to a modified project.
        /// </summary>
        internal static string discard_changes_caption {
            get {
                return ResourceManager.GetString("discard_changes_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to discard all modifications made to this
        ///project and revert it to its last saved state?
        ///You cannot undo this operation..
        /// </summary>
        internal static string discard_changes_text {
            get {
                return ResourceManager.GetString("discard_changes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty label.
        /// </summary>
        internal static string empty_label_warning_caption {
            get {
                return ResourceManager.GetString("empty_label_warning_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section cannot have an empty label..
        /// </summary>
        internal static string empty_label_warning_text {
            get {
                return ResourceManager.GetString("empty_label_warning_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;table of contents.
        /// </summary>
        internal static string hide_toc_label {
            get {
                return ResourceManager.GetString("hide_toc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find path to asset directory..
        /// </summary>
        internal static string missing_asset_path {
            get {
                return ResourceManager.GetString("missing_asset_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string mono {
            get {
                return ResourceManager.GetString("mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        internal static string name_already_exists_caption {
            get {
                return ResourceManager.GetString("name_already_exists_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not rename item `{0}&apos; as this name is already in use in the project..
        /// </summary>
        internal static string name_already_exists_text {
            get {
                return ResourceManager.GetString("name_already_exists_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string new_project {
            get {
                return ResourceManager.GetString("new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New strip.
        /// </summary>
        internal static string new_strip_label {
            get {
                return ResourceManager.GetString("new_strip_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input device found.
        /// </summary>
        internal static string no_input_device_caption {
            get {
                return ResourceManager.GetString("no_input_device_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not select and audio input device: node found. Sorry :(.
        /// </summary>
        internal static string no_input_device_text {
            get {
                return ResourceManager.GetString("no_input_device_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is currently open..
        /// </summary>
        internal static string no_open_project {
            get {
                return ResourceManager.GetString("no_open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio output device found.
        /// </summary>
        internal static string no_output_device_caption {
            get {
                return ResourceManager.GetString("no_output_device_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not select an audio output device: none found. Sorry :(.
        /// </summary>
        internal static string no_output_device_text {
            get {
                return ResourceManager.GetString("no_output_device_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obi.
        /// </summary>
        internal static string obi {
            get {
                return ResourceManager.GetString("obi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening project file.
        /// </summary>
        internal static string open_project_error_caption {
            get {
                return ResourceManager.GetString("open_project_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read XUK file {0}..
        /// </summary>
        internal static string open_project_error_text {
            get {
                return ResourceManager.GetString("open_project_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened XUK file {0}..
        /// </summary>
        internal static string opened_project {
            get {
                return ResourceManager.GetString("opened_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace project?.
        /// </summary>
        internal static string overwrite_file_caption {
            get {
                return ResourceManager.GetString("overwrite_file_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists.
        ///Do you want to replace the project contained in this file?.
        /// </summary>
        internal static string overwrite_file_text {
            get {
                return ResourceManager.GetString("overwrite_file_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create project directory {0}..
        /// </summary>
        internal static string project_directory_creation_error {
            get {
                return ResourceManager.GetString("project_directory_creation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Record.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string redo_label {
            get {
                return ResourceManager.GetString("redo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename node.
        /// </summary>
        internal static string rename_command_label {
            get {
                return ResourceManager.GetString("rename_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file {0}. ({1}).
        /// </summary>
        internal static string report_delete_error {
            get {
                return ResourceManager.GetString("report_delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resize strip.
        /// </summary>
        internal static string resize_strip {
            get {
                return ResourceManager.GetString("resize_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings.
        /// </summary>
        internal static string save_settings_error_caption {
            get {
                return ResourceManager.GetString("save_settings_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while trying to save the settings:
        ///&quot;{0}&quot;
        ///As a result, changes to the settings made during this session have not been saved.
        ///Oh well..
        /// </summary>
        internal static string save_settings_error_text {
            get {
                return ResourceManager.GetString("save_settings_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved XUK file {0}..
        /// </summary>
        internal static string saved_project {
            get {
                return ResourceManager.GetString("saved_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;table of contents.
        /// </summary>
        internal static string show_toc_label {
            get {
                return ResourceManager.GetString("show_toc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiding table of contents..
        /// </summary>
        internal static string status_toc_hidden {
            get {
                return ResourceManager.GetString("status_toc_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing table of contents..
        /// </summary>
        internal static string status_toc_shown {
            get {
                return ResourceManager.GetString("status_toc_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        internal static string stereo {
            get {
                return ResourceManager.GetString("stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string undo_label {
            get {
                return ResourceManager.GetString("undo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obi project file (*.xuk)|*.xuk|Any file|*.*.
        /// </summary>
        internal static string xuk_filter {
            get {
                return ResourceManager.GetString("xuk_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of XUK file is not the current version (expected {0} but got {1} instead.).
        /// </summary>
        internal static string xuk_version_mismatch {
            get {
                return ResourceManager.GetString("xuk_version_mismatch", resourceCulture);
            }
        }
    }
}
