//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Obi.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add sub-section.
        /// </summary>
        internal static string add_child_command_label {
            get {
                return ResourceManager.GetString("add_child_command_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list of recent projects?.
        /// </summary>
        internal static string clear_recent_caption {
            get {
                return ResourceManager.GetString("clear_recent_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the list of recent projects?
        ///You cannot undo this operation..
        /// </summary>
        internal static string clear_recent_text {
            get {
                return ResourceManager.GetString("clear_recent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing a modified project.
        /// </summary>
        internal static string closed_project_caption {
            get {
                return ResourceManager.GetString("closed_project_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close a project with unsaved modifications.
        ///Do you want to save these modifications before closing the project?.
        /// </summary>
        internal static string closed_project_text {
            get {
                return ResourceManager.GetString("closed_project_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Appended new strip {0}.
        /// </summary>
        internal static string debug_appended_strip {
            get {
                return ResourceManager.GetString("debug_appended_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Created project.
        /// </summary>
        internal static string debug_created_project {
            get {
                return ResourceManager.GetString("debug_created_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Opened project from XUK file {0}.
        /// </summary>
        internal static string debug_opened_project {
            get {
                return ResourceManager.GetString("debug_opened_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Saved project to XUK file {0}.
        /// </summary>
        internal static string debug_saved_project {
            get {
                return ResourceManager.GetString("debug_saved_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Touched project.
        /// </summary>
        internal static string debug_touched_project {
            get {
                return ResourceManager.GetString("debug_touched_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] User profile: {0}.
        /// </summary>
        internal static string debug_user_profile {
            get {
                return ResourceManager.GetString("debug_user_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled section.
        /// </summary>
        internal static string default_section_label {
            get {
                return ResourceManager.GetString("default_section_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarding changes to a modified project.
        /// </summary>
        internal static string discard_changes_caption {
            get {
                return ResourceManager.GetString("discard_changes_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to discard all modifications made to this
        ///project and revert it to its last saved state?
        ///You cannot undo this operation..
        /// </summary>
        internal static string discard_changes_text {
            get {
                return ResourceManager.GetString("discard_changes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty label.
        /// </summary>
        internal static string empty_label_warning_caption {
            get {
                return ResourceManager.GetString("empty_label_warning_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section cannot have an empty label..
        /// </summary>
        internal static string empty_label_warning_text {
            get {
                return ResourceManager.GetString("empty_label_warning_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;table of contents.
        /// </summary>
        internal static string hide_toc_label {
            get {
                return ResourceManager.GetString("hide_toc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string new_project {
            get {
                return ResourceManager.GetString("new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New strip.
        /// </summary>
        internal static string new_strip_label {
            get {
                return ResourceManager.GetString("new_strip_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is currently open..
        /// </summary>
        internal static string no_open_project {
            get {
                return ResourceManager.GetString("no_open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obi.
        /// </summary>
        internal static string obi {
            get {
                return ResourceManager.GetString("obi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening project file.
        /// </summary>
        internal static string open_project_error_caption {
            get {
                return ResourceManager.GetString("open_project_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read XUK file {0}..
        /// </summary>
        internal static string open_project_error_text {
            get {
                return ResourceManager.GetString("open_project_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string redo_label {
            get {
                return ResourceManager.GetString("redo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resize strip.
        /// </summary>
        internal static string resize_strip {
            get {
                return ResourceManager.GetString("resize_strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings.
        /// </summary>
        internal static string save_settings_error_caption {
            get {
                return ResourceManager.GetString("save_settings_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while trying to save the settings:
        ///&quot;{0}&quot;
        ///As a result, changes to the settings made during this session have not been saved.
        ///Oh well..
        /// </summary>
        internal static string save_settings_error_text {
            get {
                return ResourceManager.GetString("save_settings_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;table of contents.
        /// </summary>
        internal static string show_toc_label {
            get {
                return ResourceManager.GetString("show_toc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiding table of contents..
        /// </summary>
        internal static string status_toc_hidden {
            get {
                return ResourceManager.GetString("status_toc_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing table of contents..
        /// </summary>
        internal static string status_toc_shown {
            get {
                return ResourceManager.GetString("status_toc_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string undo_label {
            get {
                return ResourceManager.GetString("undo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string untitled {
            get {
                return ResourceManager.GetString("untitled", resourceCulture);
            }
        }
    }
}
